// <auto-generated />
using System;
using Greenhouse_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Greenhouse_API.Migrations
{
    [DbContext(typeof(GreenHouseDbContext))]
    [Migration("20260114005055_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Greenhouse_API.Models.Fertilizer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlantId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("Fertilizers");
                });

            modelBuilder.Entity("Greenhouse_API.Models.Observation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlantId")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("Observations");
                });

            modelBuilder.Entity("Greenhouse_API.Models.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("AcquiredDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("MomId")
                        .HasColumnType("integer");

                    b.Property<int>("SpecimenId")
                        .HasColumnType("integer");

                    b.Property<int>("ZoneId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MomId");

                    b.HasIndex("SpecimenId");

                    b.HasIndex("ZoneId");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("Greenhouse_API.Models.PlantHumidityRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("InRange")
                        .HasColumnType("boolean");

                    b.Property<int>("PlantId")
                        .HasColumnType("integer");

                    b.Property<float>("RecordPct")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("PlantHumidityRecords");
                });

            modelBuilder.Entity("Greenhouse_API.Models.PlantSensorAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlantId")
                        .HasColumnType("integer");

                    b.Property<int>("Reason")
                        .HasColumnType("integer");

                    b.Property<string>("SensorType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("PlantAlerts");
                });

            modelBuilder.Entity("Greenhouse_API.Models.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("LastSeen")
                        .HasColumnType("boolean");

                    b.Property<string>("SensorCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("ZoneId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.ToTable("Sensors");
                });

            modelBuilder.Entity("Greenhouse_API.Models.SoilHumidityCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("MaxHumidityPct")
                        .HasColumnType("real");

                    b.Property<float>("MinHumidityPct")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SoilHumidityCategories");
                });

            modelBuilder.Entity("Greenhouse_API.Models.Specimen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SoilHumidityCatId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SoilHumidityCatId");

                    b.ToTable("Specimens");
                });

            modelBuilder.Entity("Greenhouse_API.Models.Watering", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("HumPctAfter")
                        .HasColumnType("real");

                    b.Property<float>("HumPctBefore")
                        .HasColumnType("real");

                    b.Property<int>("PlantId")
                        .HasColumnType("integer");

                    b.Property<int>("WaterQuantityMl")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("Waterings");
                });

            modelBuilder.Entity("Greenhouse_API.Models.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("ZoneCategoryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ZoneCategoryId");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("Greenhouse_API.Models.ZoneCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("HumidityMaxPct")
                        .HasColumnType("real");

                    b.Property<float>("HumidityMinPct")
                        .HasColumnType("real");

                    b.Property<float>("LuminosityMaxLux")
                        .HasColumnType("real");

                    b.Property<float>("LuminosityMinLux")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float?>("PressureMaxPa")
                        .HasColumnType("real");

                    b.Property<float?>("PressureMinPa")
                        .HasColumnType("real");

                    b.Property<float>("TemperatureMaxC")
                        .HasColumnType("real");

                    b.Property<float>("TemperatureMinC")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("ZoneCategories");
                });

            modelBuilder.Entity("Greenhouse_API.Models.ZonePressureRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("RecordedHPa")
                        .HasColumnType("real");

                    b.Property<int>("SensorId")
                        .HasColumnType("integer");

                    b.Property<int>("ZoneId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SensorId");

                    b.HasIndex("ZoneId");

                    b.ToTable("ZonePressureRecords");
                });

            modelBuilder.Entity("Greenhouse_API.Models.ZoneRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("InRange")
                        .HasColumnType("boolean");

                    b.Property<float>("Record")
                        .HasColumnType("real");

                    b.Property<int>("SensorId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("ZoneId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SensorId");

                    b.HasIndex("ZoneId");

                    b.ToTable("ZoneRecords");
                });

            modelBuilder.Entity("Greenhouse_API.Models.ZoneSensorAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Reason")
                        .HasColumnType("integer");

                    b.Property<int>("SensorId")
                        .HasColumnType("integer");

                    b.Property<int>("SensorType")
                        .HasColumnType("integer");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SensorId");

                    b.HasIndex("ZoneId");

                    b.ToTable("ZoneAlerts");
                });

            modelBuilder.Entity("Greenhouse_API.Models.Fertilizer", b =>
                {
                    b.HasOne("Greenhouse_API.Models.Plant", "Plant")
                        .WithMany("Fertilizers")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("Greenhouse_API.Models.Observation", b =>
                {
                    b.HasOne("Greenhouse_API.Models.Plant", "Plant")
                        .WithMany("Observations")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("Greenhouse_API.Models.Plant", b =>
                {
                    b.HasOne("Greenhouse_API.Models.Plant", "Mom")
                        .WithMany("InverseMom")
                        .HasForeignKey("MomId");

                    b.HasOne("Greenhouse_API.Models.Specimen", "Specimen")
                        .WithMany("Plants")
                        .HasForeignKey("SpecimenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Greenhouse_API.Models.Zone", "Zone")
                        .WithMany("Plants")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mom");

                    b.Navigation("Specimen");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Greenhouse_API.Models.PlantHumidityRecord", b =>
                {
                    b.HasOne("Greenhouse_API.Models.Plant", "Plant")
                        .WithMany("PlantHumidityRecords")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("Greenhouse_API.Models.PlantSensorAlert", b =>
                {
                    b.HasOne("Greenhouse_API.Models.Plant", "Plant")
                        .WithMany("PlantAlerts")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("Greenhouse_API.Models.Sensor", b =>
                {
                    b.HasOne("Greenhouse_API.Models.Zone", "Zone")
                        .WithMany("Sensors")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Greenhouse_API.Models.Specimen", b =>
                {
                    b.HasOne("Greenhouse_API.Models.SoilHumidityCategory", "SoilHumidityCat")
                        .WithMany("Specimen")
                        .HasForeignKey("SoilHumidityCatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SoilHumidityCat");
                });

            modelBuilder.Entity("Greenhouse_API.Models.Watering", b =>
                {
                    b.HasOne("Greenhouse_API.Models.Plant", "Plant")
                        .WithMany("Waterings")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("Greenhouse_API.Models.Zone", b =>
                {
                    b.HasOne("Greenhouse_API.Models.ZoneCategory", "ZoneCategory")
                        .WithMany("Zones")
                        .HasForeignKey("ZoneCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ZoneCategory");
                });

            modelBuilder.Entity("Greenhouse_API.Models.ZonePressureRecord", b =>
                {
                    b.HasOne("Greenhouse_API.Models.Sensor", "Sensor")
                        .WithMany("ZonePressureRecords")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Greenhouse_API.Models.Zone", "Zone")
                        .WithMany("ZonePressureRecords")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Greenhouse_API.Models.ZoneRecord", b =>
                {
                    b.HasOne("Greenhouse_API.Models.Sensor", "Sensor")
                        .WithMany("ZoneRecords")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Greenhouse_API.Models.Zone", "Zone")
                        .WithMany("ZoneRecords")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Greenhouse_API.Models.ZoneSensorAlert", b =>
                {
                    b.HasOne("Greenhouse_API.Models.Sensor", "ZoneSensor")
                        .WithMany()
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Greenhouse_API.Models.Zone", null)
                        .WithMany("ZoneAlerts")
                        .HasForeignKey("ZoneId");

                    b.Navigation("ZoneSensor");
                });

            modelBuilder.Entity("Greenhouse_API.Models.Plant", b =>
                {
                    b.Navigation("Fertilizers");

                    b.Navigation("InverseMom");

                    b.Navigation("Observations");

                    b.Navigation("PlantAlerts");

                    b.Navigation("PlantHumidityRecords");

                    b.Navigation("Waterings");
                });

            modelBuilder.Entity("Greenhouse_API.Models.Sensor", b =>
                {
                    b.Navigation("ZonePressureRecords");

                    b.Navigation("ZoneRecords");
                });

            modelBuilder.Entity("Greenhouse_API.Models.SoilHumidityCategory", b =>
                {
                    b.Navigation("Specimen");
                });

            modelBuilder.Entity("Greenhouse_API.Models.Specimen", b =>
                {
                    b.Navigation("Plants");
                });

            modelBuilder.Entity("Greenhouse_API.Models.Zone", b =>
                {
                    b.Navigation("Plants");

                    b.Navigation("Sensors");

                    b.Navigation("ZoneAlerts");

                    b.Navigation("ZonePressureRecords");

                    b.Navigation("ZoneRecords");
                });

            modelBuilder.Entity("Greenhouse_API.Models.ZoneCategory", b =>
                {
                    b.Navigation("Zones");
                });
#pragma warning restore 612, 618
        }
    }
}
